export type Pool = {
  id: string;
  pair: string;
  dex: "Raydium" | "Orca";
  status: "dead" | "dying" | "weak";
  healthScore: number;
  priceGapPct: number;
  realProfitUsd: number;
  confidenceScore: number;
  daysSinceLastTrade: number;
  tvlCurrent: number;
  tvlPeak: number;
  lpEarned30d: number;
  botExtracted30d: number;
  abandonProbability5d: number;
  verdict: string;
};

export const mockPools: Pool[] = [
  {
    id: "pool-1",
    pair: "SOL/BONK",
    dex: "Raydium",
    status: "dead",
    healthScore: 12,
    priceGapPct: 14.5,
    realProfitUsd: 124.5,
    confidenceScore: 4,
    daysSinceLastTrade: 45,
    tvlCurrent: 1200,
    tvlPeak: 450000,
    lpEarned30d: 0.45,
    botExtracted30d: 450.2,
    abandonProbability5d: 98,
    verdict: "Complete liquidity abandonment. LP tokens burned, no active market makers. Bots extracting remaining value via micro-arbitrage.",
  },
  {
    id: "pool-2",
    pair: "JUP/USDC",
    dex: "Orca",
    status: "dying",
    healthScore: 34,
    priceGapPct: 8.2,
    realProfitUsd: 45.2,
    confidenceScore: 3,
    daysSinceLastTrade: 12,
    tvlCurrent: 8500,
    tvlPeak: 1200000,
    lpEarned30d: 12.5,
    botExtracted30d: 890.4,
    abandonProbability5d: 75,
    verdict: "Severe volume decay. Primary liquidity providers have migrated to concentrated pools. Price oracle divergence increasing.",
  },
  {
    id: "pool-3",
    pair: "WIF/SOL",
    dex: "Raydium",
    status: "weak",
    healthScore: 58,
    priceGapPct: 3.1,
    realProfitUsd: 12.8,
    confidenceScore: 2,
    daysSinceLastTrade: 2,
    tvlCurrent: 45000,
    tvlPeak: 800000,
    lpEarned30d: 145.2,
    botExtracted30d: 320.1,
    abandonProbability5d: 42,
    verdict: "Fragmented liquidity. Occasional retail trades mask underlying structural weakness. High slippage on standard order sizes.",
  },
  {
    id: "pool-4",
    pair: "SAMO/USDC",
    dex: "Orca",
    status: "dead",
    healthScore: 8,
    priceGapPct: 22.4,
    realProfitUsd: 8.5,
    confidenceScore: 4,
    daysSinceLastTrade: 89,
    tvlCurrent: 450,
    tvlPeak: 250000,
    lpEarned30d: 0.01,
    botExtracted30d: 120.5,
    abandonProbability5d: 99,
    verdict: "Terminal state. Gas fees exceed potential arbitrage profit for 95% of transactions. Zombie pool.",
  },
  {
    id: "pool-5",
    pair: "PYTH/SOL",
    dex: "Raydium",
    status: "dying",
    healthScore: 28,
    priceGapPct: 11.5,
    realProfitUsd: 67.3,
    confidenceScore: 3,
    daysSinceLastTrade: 18,
    tvlCurrent: 3200,
    tvlPeak: 600000,
    lpEarned30d: 4.2,
    botExtracted30d: 560.8,
    abandonProbability5d: 82,
    verdict: "Systematic extraction by MEV bots. Retail liquidity providers are unknowingly subsidizing toxic flow.",
  },
  {
    id: "pool-6",
    pair: "DUST/USDC",
    dex: "Raydium",
    status: "dead",
    healthScore: 15,
    priceGapPct: 18.2,
    realProfitUsd: 34.1,
    confidenceScore: 4,
    daysSinceLastTrade: 62,
    tvlCurrent: 890,
    tvlPeak: 340000,
    lpEarned30d: 0.12,
    botExtracted30d: 230.4,
    abandonProbability5d: 95,
    verdict: "Orphaned contract. Project team abandoned token. Remaining liquidity is permanently trapped due to lost keys.",
  },
  {
    id: "pool-7",
    pair: "HNT/SOL",
    dex: "Orca",
    status: "weak",
    healthScore: 62,
    priceGapPct: 2.8,
    realProfitUsd: 9.4,
    confidenceScore: 2,
    daysSinceLastTrade: 1,
    tvlCurrent: 85000,
    tvlPeak: 1500000,
    lpEarned30d: 320.5,
    botExtracted30d: 410.2,
    abandonProbability5d: 35,
    verdict: "Liquidity transition phase. Capital is slowly migrating to newer pool versions. Still functional but degrading.",
  },
  {
    id: "pool-8",
    pair: "MNGO/USDC",
    dex: "Raydium",
    status: "dying",
    healthScore: 41,
    priceGapPct: 6.5,
    realProfitUsd: 22.7,
    confidenceScore: 3,
    daysSinceLastTrade: 8,
    tvlCurrent: 12500,
    tvlPeak: 950000,
    lpEarned30d: 28.4,
    botExtracted30d: 670.3,
    abandonProbability5d: 68,
    verdict: "Imbalanced reserves. One side of the pair is nearly depleted, causing exponential slippage curves.",
  },
  {
    id: "pool-9",
    pair: "RAY/USDC",
    dex: "Raydium",
    status: "weak",
    healthScore: 55,
    priceGapPct: 4.2,
    realProfitUsd: 15.6,
    confidenceScore: 2,
    daysSinceLastTrade: 3,
    tvlCurrent: 55000,
    tvlPeak: 2000000,
    lpEarned30d: 180.2,
    botExtracted30d: 290.5,
    abandonProbability5d: 48,
    verdict: "Legacy pool structure. Outperformed by concentrated liquidity alternatives. Slow capital bleed.",
  },
  {
    id: "pool-10",
    pair: "ORCA/SOL",
    dex: "Orca",
    status: "dying",
    healthScore: 38,
    priceGapPct: 7.8,
    realProfitUsd: 38.9,
    confidenceScore: 3,
    daysSinceLastTrade: 15,
    tvlCurrent: 9800,
    tvlPeak: 850000,
    lpEarned30d: 15.6,
    botExtracted30d: 720.1,
    abandonProbability5d: 72,
    verdict: "Stale pricing. Oracle updates are infrequent, creating persistent arbitrage windows for sophisticated actors.",
  },
  {
    id: "pool-11",
    pair: "SLND/USDC",
    dex: "Raydium",
    status: "dead",
    healthScore: 5,
    priceGapPct: 28.5,
    realProfitUsd: 2.1,
    confidenceScore: 4,
    daysSinceLastTrade: 112,
    tvlCurrent: 150,
    tvlPeak: 180000,
    lpEarned30d: 0.0,
    botExtracted30d: 45.8,
    abandonProbability5d: 99,
    verdict: "Absolute zero state. No organic trading activity for over a quarter. Purely a target for dust collection.",
  },
  {
    id: "pool-12",
    pair: "CROWN/SOL",
    dex: "Orca",
    status: "weak",
    healthScore: 65,
    priceGapPct: 2.1,
    realProfitUsd: 7.2,
    confidenceScore: 2,
    daysSinceLastTrade: 1,
    tvlCurrent: 110000,
    tvlPeak: 500000,
    lpEarned30d: 450.8,
    botExtracted30d: 380.4,
    abandonProbability5d: 25,
    verdict: "Marginal inefficiency. Spread is tight enough to deter casual arbitrage, but wide enough for optimized MEV.",
  }
];
